CLIENT_HELLO = "CLIENT_HELLO"
SERVER_HELLO = "SERVER_HELLO"

UPLOAD_REQUEST = "UPLOAD_REQUEST"
UPLOAD_ACK = "UPLOAD_ACK"

LIST_REQUEST = "LIST_REQUEST"
LIST_RESPONSE = "LIST_RESPONSE"

DOWNLOAD_REQUEST = "DOWNLOAD_REQUEST"
DOWNLOAD_RESPONSE = "DOWNLOAD_RESPONSE"

ERROR = "ERROR"