"""
This file is contain our variables
We use them in (server.py)
"""

# we use these variables in server.py
CLIENT_HELLO = "CLIENT_HELLO"
SERVER_HELLO = "SERVER_HELLO"

UPLOAD_REQUEST = "UPLOAD_REQUEST"
UPLOAD_ACK = "UPLOAD_ACK"

LIST_REQUEST = "LIST_REQUEST"
LIST_RESPONSE = "LIST_RESPONSE"

DOWNLOAD_REQUEST = "DOWNLOAD_REQUEST"
DOWNLOAD_RESPONSE = "DOWNLOAD_RESPONSE"

REVOKE_REQUEST = "REVOKE_REQUEST"
REVOKE_ACK = "REVOKE_ACK"

ERROR = "ERROR"

### this is not important, we can delete it.
CLIENT_AUTH_PROOF = "CLIENT_AUTH_PROOF"
SERVER_AUTH_PROOF = "SERVER_AUTH_PROOF"
SESSION_READY = "SESSION_READY"
###
